Repository Django-Wanted-Internship-3-Team/repo1_feed-service, pull requests merged in 2023-10, with the labels that each got.

#15 Django 프로젝트 설정
  .env.example
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/pull_request_template.md
  .github/workflow/CI.yml
  .gitignore
  .gitmessage.txt
  .pre-commit-config.yaml
  config/__init__.py
  config/asgi.py
  config/settings.py
  config/urls.py
  config/wsgi.py
  likes/__init__.py
  likes/admin.py
  likes/apps.py
  likes/migrations/__init__.py
  likes/models.py
  likes/tests.py
  likes/views.py
  manage.py
  poetry.lock
  posts/__init__.py
  posts/admin.py
  posts/apps.py
  posts/migrations/__init__.py
  posts/models.py
  posts/tests.py
  posts/views.py
  pyproject.toml
  setup.cfg
  shares/__init__.py
  shares/admin.py
  shares/apps.py
  shares/migrations/__init__.py
  shares/models.py
  shares/tests.py
  shares/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: enhancement

#16 User, Post 모델 작성
  .github/workflows/CI.yml
  config/settings.py
  likes/admin.py
  likes/models.py
  posts/migrations/0001_initial.py
  posts/models.py
  shares/admin.py
  shares/models.py
  users/managers.py
  users/migrations/0001_initial.py
  users/models.py
Labels: feature

#18 통계 조회 API 작성
  .github/workflows/CI.yml
  Dockerfile
  common/__init__.py
  common/apps.py
  common/dacorator.py
  common/exceptions.py
  common/tests/__init__.py
  common/tests/decorator/__init__.py
  common/tests/decorator/test_query_parameter_decorator.py
  common/tests/utils/__init__.py
  common/tests/utils/test_date_utils.py
  common/urls.py
  common/utils.py
  common/views.py
  config/settings.py
  config/urls.py
  docker-compose.yml
  poetry.lock
  posts/serializers.py
  posts/tests.py
  posts/tests/__init__.py
  posts/tests/views/__init__.py
  posts/tests/views/test_statics_list_view.py
  posts/urls.py
  posts/views.py
  pyproject.toml
Labels: enhancement

#17 게시물 좋아요 API 작성
  config/urls.py
  likes/serializers.py
  likes/tests.py
  likes/urls.py
  likes/views.py
  posts/migrations/0002_post_content_id.py
  posts/models.py
Labels: feature

#19 회원가입 API 작성
  common/decorator.py
  common/exceptions.py
  common/views.py
  config/settings.py
  config/urls.py
  poetry.lock
  posts/tests/views/test_statistics_list_view.py
  posts/views.py
  users/managers.py
  users/migrations/0002_user_username.py
  users/models.py
  users/serializers.py
  users/tests.py
  users/tests/__init__.py
  users/tests/views/__init__.py
  users/tests/views/test_signup_view.py
  users/urls.py
  users/views.py
Labels: feature

#20 게시물 목록 API 작성
  .pre-commit-config.yaml
  config/settings.py
  poetry.lock
  posts/filters.py
  posts/migrations/0001_initial.py
  posts/migrations/0002_post_content_id.py
  posts/paginations.py
  posts/serializers.py
  posts/tests/views/test_posts_list_view.py
  posts/tests/views/test_statistics_list_view.py
  posts/urls.py
  posts/views.py
  pyproject.toml
  users/migrations/0001_initial.py
  users/migrations/0002_user_username.py
Labels: feature

#23 게시물 공유(API)
  config/urls.py
  shares/serializers.py
  shares/tests.py
  shares/tests/__init__.py
  shares/tests/test_shares_api.py
  shares/urls.py
  shares/views.py
Labels: feature

#24 게시물 상세 API 작성
  posts/apps.py
  posts/serializers.py
  posts/signals.py
  posts/tests/views/test_posts_detail_view.py
  posts/urls.py
  posts/views.py
Labels: feature, test

#26 Login API 구현
  common/utils.py
  config/settings.py
  users/serializers.py
  users/tests/views/test_confirm_user_view.py
  users/tests/views/test_login_view.py
  users/urls.py
  users/views.py
Labels: feature
